version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mh
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password

  backend:
    build: .
    ports:
    - "80:80"
    links:
    - "postgres"
    environment:
      POSTGRES_ADDRESS: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mh
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      BACKEND_PORT: 80
